import type { ServiceCategory } from '@/shared/lib/types';

export type DefaultServiceSeed = {
  serviceName: string;
  description: string;
  duration: number;
  price: number;
  category: ServiceCategory;
};

export const DEFAULT_SERVICES: DefaultServiceSeed[] = [
  {
    serviceName: 'Semi-permanent manicure + semi-permanent pedicure + classic cleaning of the sole of the foot',
    description: '',
    duration: 180,
    price: 125,
    category: 'nail-art-care-combinations',
  },
  {
    serviceName: 'Gel manicure (length 1-2) + semi-permanent pedicure + classic cleaning of the sole of the foot',
    description: '',
    duration: 180,
    price: 125,
    category: 'nail-art-care-combinations',
  },
  {
    serviceName: 'Hygienic manicure + hygienic pedicure + classic cleaning of the sole of the foot',
    description: '',
    duration: 90,
    price: 70,
    category: 'nail-art-care-combinations',
  },
  {
    serviceName: 'Semi-permanent manicure + semi-permanent pedicure',
    description: '',
    duration: 150,
    price: 105,
    category: 'nail-art-care-combinations',
  },
  {
    serviceName: 'Gel manicure (length 1-2) + semi-permanent pedicure',
    description: '',
    duration: 150,
    price: 105,
    category: 'nail-art-care-combinations',
  },
  {
    serviceName: 'Hygienic manicure + hygienic pedicure',
    description: '',
    duration: 75,
    price: 50,
    category: 'nail-art-care-combinations',
  },
  {
    serviceName: 'Semi-permanent gel polish',
    description: '',
    duration: 90,
    price: 55,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Gel refill (length 1-2)',
    description: '',
    duration: 100,
    price: 55,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Gel refill (length 3-4)',
    description: '',
    duration: 120,
    price: 60,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Extensions (length 1-2)',
    description: '',
    duration: 120,
    price: 65,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Extensions (length 3-4)',
    description: '',
    duration: 150,
    price: 80,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Extensions (length 5-7)',
    description: '',
    duration: 210,
    price: 100,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Special techniques - French Glass / French Interior',
    description: '',
    duration: 240,
    price: 120,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Hygienic manicure',
    description: '',
    duration: 30,
    price: 25,
    category: 'nail-art-care-manicure',
  },
  {
    serviceName: 'Semi-permanent gel polish (feet)',
    description: '',
    duration: 60,
    price: 50,
    category: 'professional-foot-services',
  },
  {
    serviceName: 'Hygienic pedicure',
    description: '',
    duration: 30,
    price: 30,
    category: 'professional-foot-services',
  },
  {
    serviceName: 'Hygienic pedicure + classic polish',
    description: '',
    duration: 40,
    price: 35,
    category: 'professional-foot-services',
  },
  {
    serviceName: 'Classic sole cleaning + hydration',
    description: '',
    duration: 20,
    price: 20,
    category: 'foot-sole-treatments',
  },
  {
    serviceName: 'Enzymatic sole peeling',
    description: '',
    duration: 30,
    price: 35,
    category: 'foot-sole-treatments',
  },
  {
    serviceName: 'Keratolytic sole treatment + hydration',
    description: '',
    duration: 50,
    price: 50,
    category: 'foot-sole-treatments',
  },
  {
    serviceName: 'Lash lamination',
    description: '',
    duration: 120,
    price: 65,
    category: 'lamination',
  },
  {
    serviceName: 'Brow lamination',
    description: '',
    duration: 60,
    price: 55,
    category: 'lamination',
  },
  {
    serviceName: 'Full package lashes + brows (lamination)',
    description: '',
    duration: 150,
    price: 115,
    category: 'lamination',
  },
  {
    serviceName: 'Brow lamination + shaping (waxing/tweezing)',
    description: '',
    duration: 50,
    price: 45,
    category: 'lamination',
  },
  {
    serviceName: 'Lash tint (standalone service)',
    description: '',
    duration: 20,
    price: 15,
    category: 'lamination',
  },
  {
    serviceName: 'Brow shaping + tint',
    description: '',
    duration: 50,
    price: 45,
    category: 'brow-services',
  },
  {
    serviceName: 'Brow shaping',
    description: '',
    duration: 30,
    price: 25,
    category: 'brow-services',
  },
  {
    serviceName: 'Brow tint',
    description: '',
    duration: 40,
    price: 25,
    category: 'brow-services',
  },
  {
    serviceName: 'Upper lip waxing',
    description: '',
    duration: 10,
    price: 15,
    category: 'brow-services',
  },
  {
    serviceName: 'Nose waxing',
    description: '',
    duration: 10,
    price: 15,
    category: 'brow-services',
  },
  {
    serviceName: 'Ear waxing',
    description: '',
    duration: 10,
    price: 15,
    category: 'brow-services',
  },
  {
    serviceName: 'Full set - Classic 1:1 (mascara effect)',
    description: '',
    duration: 120,
    price: 75,
    category: 'lash-extensions',
  },
  {
    serviceName: 'Full set - 2D volume',
    description: '',
    duration: 130,
    price: 85,
    category: 'lash-extensions',
  },
  {
    serviceName: 'Full set - Wet look volume',
    description: '',
    duration: 140,
    price: 90,
    category: 'lash-extensions',
  },
  {
    serviceName: 'Full set - 3D volume',
    description: '',
    duration: 150,
    price: 95,
    category: 'lash-extensions',
  },
  {
    serviceName: 'Full set - Mega volume',
    description: '',
    duration: 180,
    price: 125,
    category: 'lash-extensions',
  },
  {
    serviceName: 'LED extensions - Classic',
    description: '',
    duration: 120,
    price: 100,
    category: 'lash-extensions',
  },
  {
    serviceName: 'LED extensions - Volume',
    description: '',
    duration: 150,
    price: 125,
    category: 'lash-extensions',
  },
  {
    serviceName: 'Refill - Classic (1:1)',
    description: '',
    duration: 120,
    price: 65,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Refill - 2D volume',
    description: '',
    duration: 120,
    price: 70,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Refill - 3D volume',
    description: '',
    duration: 120,
    price: 75,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Refill - Wet look volume',
    description: '',
    duration: 120,
    price: 80,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Refill - Mega volume',
    description: '',
    duration: 120,
    price: 90,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Refill - LED classic',
    description: '',
    duration: 90,
    price: 90,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Refill - LED volume',
    description: '',
    duration: 120,
    price: 100,
    category: 'lash-extension-refill',
  },
  {
    serviceName: 'Lash extension removal',
    description: '',
    duration: 30,
    price: 30,
    category: 'lash-extension-removal',
  },
  {
    serviceName: 'Brows - Powder technique',
    description: '',
    duration: 210,
    price: 350,
    category: 'semi-permanent-makeup',
  },
  {
    serviceName: 'Lips',
    description: '',
    duration: 240,
    price: 350,
    category: 'semi-permanent-makeup',
  },
  {
    serviceName: 'Eye contour (lash density line)',
    description: '',
    duration: 120,
    price: 200,
    category: 'semi-permanent-makeup',
  },
  {
    serviceName: 'Classic eyeliner / shaded eyeliner',
    description: '',
    duration: 210,
    price: 230,
    category: 'semi-permanent-makeup',
  },
  {
    serviceName: 'Touch-up (any procedure)',
    description: '',
    duration: 120,
    price: 200,
    category: 'semi-permanent-makeup',
  },
  {
    serviceName: 'Day makeup',
    description: '',
    duration: 90,
    price: 100,
    category: 'professional-makeup',
  },
  {
    serviceName: 'Evening makeup',
    description: '',
    duration: 90,
    price: 120,
    category: 'professional-makeup',
  },
  {
    serviceName: 'Bridal makeup (with trial included)',
    description: '',
    duration: 120,
    price: 350,
    category: 'professional-makeup',
  },
  {
    serviceName: 'Bridal makeup (without trial)',
    description: '',
    duration: 120,
    price: 250,
    category: 'professional-makeup',
  },
];
